@startuml
hide empty members

package view {
    class GptUiController
    together {
        class GptUiApplication
        class "AnswerController" as grammarAnswerController <<GRAMMAR>>
        class "AnswerController" as shortAnswerController <<SHORT>>
        class "AnswerController" as claudeAnswerController <<CLAUDE>>
        class "AnswerController" as gcpAnswerController <<GCP>>
        class HistoryController
        class QuestionController
        class ThemeController
    }
}

package viewmodel {
    class "AnswerVM" as grammarAnswerVM <<GRAMMAR>>
    class "AnswerVM" as shortAnswerVM <<SHORT>>
    class "AnswerVM" as claudeAnswerVM <<CLAUDE>>
    class "AnswerVM" as gcpAnswerVM <<GCP>>
    class GptUiVM
    class HistoryVM
    class QuestionVM
    class ThemeVM
    class ViewModelMediator
}

package model{
    class StateModel
    class ClipboardModel
    class ConfigModel
    class FileModel
    class QuestionModel
    class StorageModel
}

ThemeController ---> ThemeVM
QuestionController ---> QuestionVM
HistoryController ---> HistoryVM
grammarAnswerController --> grammarAnswerVM
shortAnswerController --> shortAnswerVM
claudeAnswerController --> claudeAnswerVM
gcpAnswerController --> gcpAnswerVM
GptUiApplication --> GptUiVM

GptUiController --> grammarAnswerController
GptUiController --> shortAnswerController
GptUiController --> claudeAnswerController
GptUiController --> gcpAnswerController

ThemeVM <--> ViewModelMediator
QuestionVM <--> ViewModelMediator
HistoryVM <--> ViewModelMediator
GptUiVM --> ViewModelMediator
grammarAnswerVM <--> ViewModelMediator
shortAnswerVM <--> ViewModelMediator
claudeAnswerVM <--> ViewModelMediator
gcpAnswerVM <--> ViewModelMediator

ThemeVM ---> StateModel
HistoryVM ---> StateModel
QuestionVM ---> StateModel
QuestionVM ---> QuestionModel
QuestionVM ---> ClipboardModel

grammarAnswerVM --> StateModel
shortAnswerVM --> StateModel
claudeAnswerVM --> StateModel
gcpAnswerVM --> StateModel

grammarAnswerVM --> QuestionModel
shortAnswerVM --> QuestionModel
claudeAnswerVM --> QuestionModel
gcpAnswerVM --> QuestionModel

grammarAnswerVM --> ClipboardModel
shortAnswerVM --> ClipboardModel
claudeAnswerVM --> ClipboardModel
gcpAnswerVM --> ClipboardModel


@enduml