@startuml
hide empty members

package view {
    class TopicPromptUiController
    together {
        class TopicPromptUiApplication
        class "AnswerController" as grammarAnswerController <<GRAMMAR>>
        class "AnswerController" as ai1AnswerController <<AI_1>>
        class "AnswerController" as ai2AnswerController <<AI_2>>
        class "AnswerController" as ai3AnswerController <<AI_3>>
        class HistoryController
        class QuestionController
        class TopicController
    }
}

package viewmodel {
    class "AnswerVM" as grammarAnswerVM <<GRAMMAR>>
    class "AnswerVM" as ai1AnswerVM <<AI_1>>
    class "AnswerVM" as ai2AnswerVM <<AI_2>>
    class "AnswerVM" as ai3AnswerVM <<AI_3>>
    class TopicPromptUiVM
    class HistoryVM
    class QuestionVM
    class TopicVM
    class ViewModelMediator
}

package model{
    class StateModel
    class ClipboardModel
    class FileModel
    class QuestionModel
    class StorageModel
}

TopicController ---> TopicVM
QuestionController ---> QuestionVM
HistoryController ---> HistoryVM
grammarAnswerController --> grammarAnswerVM
ai1AnswerController --> ai1AnswerVM
ai2AnswerController --> ai2AnswerVM
ai3AnswerController --> ai3AnswerVM
TopicPromptUiApplication --> TopicPromptUiVM

TopicPromptUiController --> grammarAnswerController
TopicPromptUiController --> ai1AnswerController
TopicPromptUiController --> ai2AnswerController
TopicPromptUiController --> ai3AnswerController

TopicPromptUiController --> TopicPromptUiVM
TopicPromptUiController --> grammarAnswerVM
TopicPromptUiController --> ai1AnswerVM
TopicPromptUiController --> ai2AnswerVM
TopicPromptUiController --> ai3AnswerVM

TopicVM <--> ViewModelMediator
QuestionVM <--> ViewModelMediator
HistoryVM <--> ViewModelMediator
TopicPromptUiVM --> ViewModelMediator
grammarAnswerVM <--> ViewModelMediator
ai1AnswerVM <--> ViewModelMediator
ai2AnswerVM <--> ViewModelMediator
ai3AnswerVM <--> ViewModelMediator

TopicVM ---> StateModel
HistoryVM ---> StateModel
QuestionVM ---> StateModel
QuestionVM ---> QuestionModel
QuestionVM ---> ClipboardModel

grammarAnswerVM --> StateModel
ai1AnswerVM --> StateModel
ai2AnswerVM --> StateModel
ai3AnswerVM --> StateModel

grammarAnswerVM --> QuestionModel
ai1AnswerVM --> QuestionModel
ai2AnswerVM --> QuestionModel
ai3AnswerVM --> QuestionModel

grammarAnswerVM --> ClipboardModel
ai1AnswerVM --> ClipboardModel
ai2AnswerVM --> ClipboardModel
ai3AnswerVM --> ClipboardModel


@enduml