@startuml
hide empty members

package model{
    class StateModel
    class ClipboardModel
    class FileModel
    class QuestionModel
    class StorageModel
    class HistorySearchModel
}
package viewmodel {
    interface QuestionVmController
    interface QuestionVmMediator
    class QuestionVmImpl

    interface TopicVmController
    interface TopicVmMediator
    interface HistoryVmController
    interface HistoryVmMediator
    interface AnswerVmController
    interface AnswerVmMediator
    interface GptUiVmController

    class GptUiVmImpl

    interface GptUiApplicationVmController
    class GptUiApplicationVmImpl

    interface AnswerMediator
    interface GptUiApplicationMediator
    interface GptUiMediator
    interface HistoryMediator
    interface QuestionMediator
    interface TopicMediator
    class ViewModelMediatorImpl
}

package view {
    class GptUiApplication
    class AnswerController
    class GptUiApplication
    class GptUiController
    class HistoryController
    class QuestionController
    class TopicController
}

GptUiApplication --> GptUiApplicationVmController

GptUiApplicationVmImpl ..|> GptUiApplicationVmController
GptUiApplicationVmImpl --> GptUiApplicationMediator

ViewModelMediatorImpl ..|> AnswerMediator
ViewModelMediatorImpl ..|> GptUiApplicationMediator
ViewModelMediatorImpl ..|> GptUiMediator
ViewModelMediatorImpl ..|> HistoryMediator
ViewModelMediatorImpl ..|> QuestionMediator
ViewModelMediatorImpl ..|> TopicMediator

ViewModelMediatorImpl --> AnswerVmMediator
ViewModelMediatorImpl --> HistoryVmMediator
ViewModelMediatorImpl --> QuestionVmMediator
ViewModelMediatorImpl --> TopicVmMediator

QuestionVmImpl ..|> QuestionVmController
QuestionVmImpl ..|> QuestionVmMediator
QuestionVmImpl --> QuestionMediator

GptUiVmImpl ..|> GptUiVmController
GptUiVmImpl --> GptUiMediator

TopicController ---> TopicVmController
QuestionController ---> QuestionVmController
HistoryController ---> HistoryVmController
AnswerController --> AnswerVmController

GptUiController "1" --> "4" AnswerController: initialize
GptUiController --> AnswerVmController
GptUiController --> GptUiVmController

StateModel --> StorageModel
QuestionModel --> StorageModel

ViewModelMediatorImpl --> StateModel
ViewModelMediatorImpl --> QuestionModel
ViewModelMediatorImpl --> ClipboardModel
ViewModelMediatorImpl --> FileModel

@enduml