@startuml
hide empty members

package model{
    class StateModel
    class ClipboardModel
    class FileModel
    class QuestionModel
    class StorageModel
    class HistorySearchModel
}
package viewmodel {
    interface QuestionVmController
    interface QuestionVmMediator
    class QuestionVmImpl

    interface TopicVmController
    interface TopicVmMediator
    interface HistoryVmController
    interface HistoryVmMediator
    interface AnswerVmController
    interface AnswerVmMediator
    interface TopicPromptUiVmController

    class TopicPromptUiVmImpl

    interface TopicPromptUiApplicationVmController
    class TopicPromptUiApplicationVmImpl

    interface AnswerMediator
    interface TopicPromptUiApplicationMediator
    interface TopicPromptUiMediator
    interface HistoryMediator
    interface QuestionMediator
    interface TopicMediator
    class ViewModelMediatorImpl
}

package view {
    class TopicPromptUiApplication
    class AnswerController
    class TopicPromptUiApplication
    class TopicPromptUiController
    class HistoryController
    class QuestionController
    class TopicController
}

TopicPromptUiApplication --> TopicPromptUiApplicationVmController

TopicPromptUiApplicationVmImpl ..|> TopicPromptUiApplicationVmController
TopicPromptUiApplicationVmImpl --> TopicPromptUiApplicationMediator

ViewModelMediatorImpl ..|> AnswerMediator
ViewModelMediatorImpl ..|> TopicPromptUiApplicationMediator
ViewModelMediatorImpl ..|> TopicPromptUiMediator
ViewModelMediatorImpl ..|> HistoryMediator
ViewModelMediatorImpl ..|> QuestionMediator
ViewModelMediatorImpl ..|> TopicMediator

ViewModelMediatorImpl --> AnswerVmMediator
ViewModelMediatorImpl --> HistoryVmMediator
ViewModelMediatorImpl --> QuestionVmMediator
ViewModelMediatorImpl --> TopicVmMediator

QuestionVmImpl ..|> QuestionVmController
QuestionVmImpl ..|> QuestionVmMediator
QuestionVmImpl --> QuestionMediator

TopicPromptUiVmImpl ..|> TopicPromptUiVmController
TopicPromptUiVmImpl --> TopicPromptUiMediator

TopicController ---> TopicVmController
QuestionController ---> QuestionVmController
HistoryController ---> HistoryVmController
AnswerController --> AnswerVmController

TopicPromptUiController "1" --> "4" AnswerController: initialize
TopicPromptUiController --> AnswerVmController
TopicPromptUiController --> TopicPromptUiVmController

StateModel --> StorageModel
QuestionModel --> StorageModel

ViewModelMediatorImpl --> StateModel
ViewModelMediatorImpl --> QuestionModel
ViewModelMediatorImpl --> ClipboardModel
ViewModelMediatorImpl --> FileModel

@enduml