@startuml
'https://plantuml.com/class-diagram

package gptui {
    package model {}
    package util {}
    package view {}
    package viewmodel {}
}

view --> viewmodel
view --> model
viewmodel --> model
viewmodel --> util
model --> util
util --> model

@enduml