@startuml
'https://plantuml.com/class-diagram

package topicpromptui {
    package core {
        package ai {}
        package util {}
        package storagefilesystem {}
    }
    package ui {
        package model {}
        package view {}
        package viewmodel {}
    }
}

view --> viewmodel
view --> storagefilesystem
view --> util
viewmodel --> model
viewmodel --> storagefilesystem
viewmodel --> util
model --> ai
model --> storagefilesystem
model --> util
storagefilesystem --> util

@enduml