@startuml
'https://plantuml.com/class-diagram

package gptui {
    package core {
        package ai {}
        package util {}
        package storagefilesystem {}
    }
    package ui {
        package model {}
        package view {}
        package viewmodel {}
    }
}

view --> viewmodel
view --> model
viewmodel --> model
viewmodel --> util
model --> util
util --> storagefilesystem
model --> ai

@enduml