@startuml
title Threads

autonumber
autoactivate on

box Main Thread
participant TopicPromptUiMain
end box

box JavaFX Application Thread
participant TopicPromptUiApplication
participant QuestionModel as QuestionModelFx
end box

box Cached Thread Pool (EXECUTOR)
participant QuestionModel as QuestionModelPool
end box

TopicPromptUiMain --> TopicPromptUiApplication **
TopicPromptUiApplication -> QuestionModelFx: requestAnswer()
QuestionModelFx -> QuestionModelPool: runAsync(send)
QuestionModelFx <-- QuestionModelPool
TopicPromptUiApplication <-- QuestionModelFx

...answer streams over SSE on the pool thread...
loop each throttled progress tick (~250ms)
QuestionModelPool ->> TopicPromptUiApplication: Platform.runLater(progressHtml)
end

QuestionModelPool ->> TopicPromptUiApplication: Platform.runLater(callback)

@enduml
